<?php

namespace Database\Seeders;

use App\Models\Coupon;
use Illuminate\Database\Seeder;

class CouponSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $coupons = [
            [
                'code' => 'WELCOME10',
                'name' => 'Welcome Discount',
                'description' => 'Get 10% off on your first order',
                'type' => 'percentage',
                'value' => 10.00,
                'min_purchase_amount' => 50.00,
                'max_discount_amount' => 20.00,
                'usage_limit' => 1000,
                'usage_limit_per_user' => 1,
                'starts_at' => now(),
                'expires_at' => now()->addMonths(3),
                'is_active' => true,
                'first_order_only' => true,
                'free_shipping' => false,
            ],
            [
                'code' => 'SAVE20',
                'name' => 'Save 20% Off',
                'description' => 'Save 20% on orders over $100',
                'type' => 'percentage',
                'value' => 20.00,
                'min_purchase_amount' => 100.00,
                'max_discount_amount' => 50.00,
                'usage_limit' => 500,
                'usage_limit_per_user' => 3,
                'starts_at' => now(),
                'expires_at' => now()->addMonths(2),
                'is_active' => true,
                'first_order_only' => false,
                'free_shipping' => false,
            ],
            [
                'code' => 'FREESHIP',
                'name' => 'Free Shipping',
                'description' => 'Get free shipping on all orders',
                'type' => 'fixed',
                'value' => 0.00,
                'min_purchase_amount' => 30.00,
                'max_discount_amount' => null,
                'usage_limit' => null,
                'usage_limit_per_user' => null,
                'starts_at' => now(),
                'expires_at' => now()->addMonths(6),
                'is_active' => true,
                'first_order_only' => false,
                'free_shipping' => true,
            ],
            [
                'code' => 'FLAT50',
                'name' => 'Flat $50 Off',
                'description' => 'Get flat $50 discount on orders over $200',
                'type' => 'fixed',
                'value' => 50.00,
                'min_purchase_amount' => 200.00,
                'max_discount_amount' => null,
                'usage_limit' => 200,
                'usage_limit_per_user' => 2,
                'starts_at' => now(),
                'expires_at' => now()->addMonth(),
                'is_active' => true,
                'first_order_only' => false,
                'free_shipping' => false,
            ],
            [
                'code' => 'SUMMER25',
                'name' => 'Summer Sale',
                'description' => '25% off summer collection',
                'type' => 'percentage',
                'value' => 25.00,
                'min_purchase_amount' => 75.00,
                'max_discount_amount' => 100.00,
                'usage_limit' => 1000,
                'usage_limit_per_user' => 5,
                'starts_at' => now(),
                'expires_at' => now()->addMonths(3),
                'is_active' => true,
                'first_order_only' => false,
                'free_shipping' => false,
            ],
            [
                'code' => 'NEWUSER15',
                'name' => 'New Customer Special',
                'description' => '15% off for new customers',
                'type' => 'percentage',
                'value' => 15.00,
                'min_purchase_amount' => 40.00,
                'max_discount_amount' => 30.00,
                'usage_limit' => 2000,
                'usage_limit_per_user' => 1,
                'starts_at' => now(),
                'expires_at' => now()->addMonths(12),
                'is_active' => true,
                'first_order_only' => true,
                'free_shipping' => false,
            ],
            [
                'code' => 'VIP100',
                'name' => 'VIP Discount',
                'description' => '$100 off for VIP customers',
                'type' => 'fixed',
                'value' => 100.00,
                'min_purchase_amount' => 500.00,
                'max_discount_amount' => null,
                'usage_limit' => 50,
                'usage_limit_per_user' => 1,
                'starts_at' => now(),
                'expires_at' => now()->addMonths(6),
                'is_active' => true,
                'first_order_only' => false,
                'free_shipping' => true,
            ],
            [
                'code' => 'EXPIRED10',
                'name' => 'Expired Coupon',
                'description' => 'This coupon has expired (for testing)',
                'type' => 'percentage',
                'value' => 10.00,
                'min_purchase_amount' => null,
                'max_discount_amount' => null,
                'usage_limit' => null,
                'usage_limit_per_user' => null,
                'starts_at' => now()->subMonths(2),
                'expires_at' => now()->subMonth(),
                'is_active' => true,
                'first_order_only' => false,
                'free_shipping' => false,
            ],
            [
                'code' => 'INACTIVE20',
                'name' => 'Inactive Coupon',
                'description' => 'This coupon is inactive (for testing)',
                'type' => 'percentage',
                'value' => 20.00,
                'min_purchase_amount' => null,
                'max_discount_amount' => null,
                'usage_limit' => null,
                'usage_limit_per_user' => null,
                'starts_at' => now(),
                'expires_at' => now()->addMonths(3),
                'is_active' => false,
                'first_order_only' => false,
                'free_shipping' => false,
            ],
            [
                'code' => 'UPCOMING30',
                'name' => 'Upcoming Sale',
                'description' => 'This coupon starts next week (for testing)',
                'type' => 'percentage',
                'value' => 30.00,
                'min_purchase_amount' => 100.00,
                'max_discount_amount' => 75.00,
                'usage_limit' => 500,
                'usage_limit_per_user' => 2,
                'starts_at' => now()->addWeek(),
                'expires_at' => now()->addMonths(2),
                'is_active' => true,
                'first_order_only' => false,
                'free_shipping' => false,
            ],
        ];

        foreach ($coupons as $coupon) {
            Coupon::create($coupon);
        }

        $this->command->info('✅ Created ' . count($coupons) . ' sample coupons');
    }
}
