<?php

namespace Database\Seeders;

use App\Models\ThemeSetting;
use Illuminate\Database\Seeder;

class ThemeSettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $themes = [
            [
                'name' => 'default',
                'label' => 'Default (Blue)',
                'is_active' => true,
                'is_predefined' => true,
                'primary_bg' => 'bg-blue-600',
                'primary_bg_hover' => 'hover:bg-blue-700',
                'primary_text' => 'text-blue-600',
                'primary_border' => 'border-blue-600',
                'sidebar_active_bg' => 'bg-blue-600',
                'button_primary_bg' => 'bg-blue-600',
                'button_primary_bg_hover' => 'hover:bg-blue-700',
                'link_text' => 'text-blue-600',
                'link_hover_text' => 'hover:text-blue-800',
                'input_focus_border' => 'focus:border-blue-500',
                'input_focus_ring' => 'focus:ring-blue-500',
                // Frontend
                'nav_bg' => 'bg-white',
                'nav_text' => 'text-gray-700',
                'nav_hover_bg' => 'hover:bg-gray-50',
                'nav_hover_text' => 'hover:text-blue-600',
                'nav_active_text' => 'text-blue-600',
                'product_card_bg' => 'bg-white',
                'product_card_border' => 'border-gray-200',
                'product_card_hover_shadow' => 'hover:shadow-lg',
                'product_title_text' => 'text-gray-900',
                'product_price_text' => 'text-blue-600',
                'product_old_price_text' => 'text-gray-400',
                'product_discount_badge_bg' => 'bg-red-500',
                'product_discount_badge_text' => 'text-white',
                'shop_button_bg' => 'bg-blue-600',
                'shop_button_hover_bg' => 'hover:bg-blue-700',
                'shop_button_text' => 'text-white',
                'cart_button_bg' => 'bg-green-600',
                'cart_button_hover_bg' => 'hover:bg-green-700',
                'cart_button_text' => 'text-white',
                'footer_bg' => 'bg-gray-900',
                'footer_text' => 'text-gray-300',
                'footer_heading_text' => 'text-white',
                'footer_link_text' => 'text-gray-400',
                'footer_link_hover_text' => 'hover:text-white',
                'hero_overlay_bg' => 'bg-blue-900',
                'hero_title_text' => 'text-white',
                'hero_subtitle_text' => 'text-blue-100',
                'hero_button_bg' => 'bg-blue-600',
                'hero_button_hover_bg' => 'hover:bg-blue-700',
                'hero_button_text' => 'text-white',
                'category_badge_bg' => 'bg-blue-100',
                'category_badge_text' => 'text-blue-800',
                'category_badge_hover_bg' => 'hover:bg-blue-200',
                'price_color' => 'text-blue-600',
                'sale_price_color' => 'text-red-500',
                'stock_available_text' => 'text-green-600',
                'stock_unavailable_text' => 'text-red-600',
                'search_input_bg' => 'bg-gray-50',
                'search_input_text' => 'text-gray-900',
                'search_input_border' => 'border-gray-300',
                'search_input_focus_border' => 'focus:border-blue-500',
                'rating_star_color' => 'text-yellow-400',
                'rating_star_empty_color' => 'text-gray-300',
                'newsletter_bg' => 'bg-blue-600',
                'newsletter_text' => 'text-white',
                'newsletter_button_bg' => 'bg-white',
                'newsletter_button_text' => 'text-blue-600',
            ],
            [
                'name' => 'green',
                'label' => 'Green Nature',
                'is_active' => false,
                'is_predefined' => true,
                'primary_bg' => 'bg-green-600',
                'primary_bg_hover' => 'hover:bg-green-700',
                'primary_text' => 'text-green-600',
                'primary_border' => 'border-green-600',
                'sidebar_active_bg' => 'bg-green-600',
                'button_primary_bg' => 'bg-green-600',
                'button_primary_bg_hover' => 'hover:bg-green-700',
                'link_text' => 'text-green-600',
                'link_hover_text' => 'hover:text-green-800',
                'input_focus_border' => 'focus:border-green-500',
                'input_focus_ring' => 'focus:ring-green-500',
                // Frontend
                'nav_bg' => 'bg-white',
                'nav_text' => 'text-gray-700',
                'nav_hover_text' => 'hover:text-green-600',
                'nav_active_text' => 'text-green-600',
                'product_price_text' => 'text-green-600',
                'shop_button_bg' => 'bg-green-600',
                'shop_button_hover_bg' => 'hover:bg-green-700',
                'cart_button_bg' => 'bg-green-700',
                'cart_button_hover_bg' => 'hover:bg-green-800',
                'hero_overlay_bg' => 'bg-green-900',
                'hero_button_bg' => 'bg-green-600',
                'hero_button_hover_bg' => 'hover:bg-green-700',
                'category_badge_bg' => 'bg-green-100',
                'category_badge_text' => 'text-green-800',
                'price_color' => 'text-green-600',
                'search_input_focus_border' => 'focus:border-green-500',
                'newsletter_bg' => 'bg-green-600',
            ],
            [
                'name' => 'red',
                'label' => 'Red Energy',
                'is_active' => false,
                'is_predefined' => true,
                'primary_bg' => 'bg-red-600',
                'primary_bg_hover' => 'hover:bg-red-700',
                'primary_text' => 'text-red-600',
                'primary_border' => 'border-red-600',
                'sidebar_active_bg' => 'bg-red-600',
                'button_primary_bg' => 'bg-red-600',
                'button_primary_bg_hover' => 'hover:bg-red-700',
                'link_text' => 'text-red-600',
                'link_hover_text' => 'hover:text-red-800',
                'input_focus_border' => 'focus:border-red-500',
                'input_focus_ring' => 'focus:ring-red-500',
                // Frontend
                'nav_bg' => 'bg-white',
                'nav_text' => 'text-gray-700',
                'nav_hover_text' => 'hover:text-red-600',
                'nav_active_text' => 'text-red-600',
                'product_price_text' => 'text-red-600',
                'shop_button_bg' => 'bg-red-600',
                'shop_button_hover_bg' => 'hover:bg-red-700',
                'cart_button_bg' => 'bg-red-700',
                'cart_button_hover_bg' => 'hover:bg-red-800',
                'hero_overlay_bg' => 'bg-red-900',
                'hero_button_bg' => 'bg-red-600',
                'hero_button_hover_bg' => 'hover:bg-red-700',
                'category_badge_bg' => 'bg-red-100',
                'category_badge_text' => 'text-red-800',
                'price_color' => 'text-red-600',
                'search_input_focus_border' => 'focus:border-red-500',
                'newsletter_bg' => 'bg-red-600',
            ],
            [
                'name' => 'purple',
                'label' => 'Purple Royal',
                'is_active' => false,
                'is_predefined' => true,
                'primary_bg' => 'bg-purple-600',
                'primary_bg_hover' => 'hover:bg-purple-700',
                'primary_text' => 'text-purple-600',
                'primary_border' => 'border-purple-600',
                'sidebar_active_bg' => 'bg-purple-600',
                'button_primary_bg' => 'bg-purple-600',
                'button_primary_bg_hover' => 'hover:bg-purple-700',
                'link_text' => 'text-purple-600',
                'link_hover_text' => 'hover:text-purple-800',
                'input_focus_border' => 'focus:border-purple-500',
                'input_focus_ring' => 'focus:ring-purple-500',
                // Frontend
                'nav_bg' => 'bg-white',
                'nav_text' => 'text-gray-700',
                'nav_hover_text' => 'hover:text-purple-600',
                'nav_active_text' => 'text-purple-600',
                'product_price_text' => 'text-purple-600',
                'shop_button_bg' => 'bg-purple-600',
                'shop_button_hover_bg' => 'hover:bg-purple-700',
                'cart_button_bg' => 'bg-purple-700',
                'cart_button_hover_bg' => 'hover:bg-purple-800',
                'hero_overlay_bg' => 'bg-purple-900',
                'hero_button_bg' => 'bg-purple-600',
                'hero_button_hover_bg' => 'hover:bg-purple-700',
                'category_badge_bg' => 'bg-purple-100',
                'category_badge_text' => 'text-purple-800',
                'price_color' => 'text-purple-600',
                'search_input_focus_border' => 'focus:border-purple-500',
                'newsletter_bg' => 'bg-purple-600',
            ],
            [
                'name' => 'dark',
                'label' => 'Dark Mode',
                'is_active' => false,
                'is_predefined' => true,
                'primary_bg' => 'bg-gray-800',
                'primary_bg_hover' => 'hover:bg-gray-900',
                'primary_text' => 'text-gray-800',
                'primary_border' => 'border-gray-800',
                'sidebar_bg' => 'bg-gray-950',
                'sidebar_active_bg' => 'bg-gray-700',
                'button_primary_bg' => 'bg-gray-800',
                'button_primary_bg_hover' => 'hover:bg-gray-900',
                'card_bg' => 'bg-gray-800',
                'card_text' => 'text-gray-100',
                'link_text' => 'text-gray-400',
                'link_hover_text' => 'hover:text-gray-200',
                'input_bg' => 'bg-gray-700',
                'input_text' => 'text-gray-100',
                'input_border' => 'border-gray-600',
                'input_focus_border' => 'focus:border-gray-500',
                'input_focus_ring' => 'focus:ring-gray-500',
            ],
            [
                'name' => 'indigo',
                'label' => 'Indigo Professional',
                'is_active' => false,
                'is_predefined' => true,
                'primary_bg' => 'bg-indigo-600',
                'primary_bg_hover' => 'hover:bg-indigo-700',
                'primary_text' => 'text-indigo-600',
                'primary_border' => 'border-indigo-600',
                'sidebar_active_bg' => 'bg-indigo-600',
                'button_primary_bg' => 'bg-indigo-600',
                'button_primary_bg_hover' => 'hover:bg-indigo-700',
                'link_text' => 'text-indigo-600',
                'link_hover_text' => 'hover:text-indigo-800',
                'input_focus_border' => 'focus:border-indigo-500',
                'input_focus_ring' => 'focus:ring-indigo-500',
                // Frontend
                'nav_bg' => 'bg-white',
                'nav_text' => 'text-gray-700',
                'nav_hover_text' => 'hover:text-indigo-600',
                'nav_active_text' => 'text-indigo-600',
                'product_price_text' => 'text-indigo-600',
                'shop_button_bg' => 'bg-indigo-600',
                'shop_button_hover_bg' => 'hover:bg-indigo-700',
                'cart_button_bg' => 'bg-indigo-700',
                'cart_button_hover_bg' => 'hover:bg-indigo-800',
                'hero_overlay_bg' => 'bg-indigo-900',
                'hero_button_bg' => 'bg-indigo-600',
                'hero_button_hover_bg' => 'hover:bg-indigo-700',
                'category_badge_bg' => 'bg-indigo-100',
                'category_badge_text' => 'text-indigo-800',
                'price_color' => 'text-indigo-600',
                'search_input_focus_border' => 'focus:border-indigo-500',
                'newsletter_bg' => 'bg-indigo-600',
            ],
        ];

        foreach ($themes as $theme) {
            ThemeSetting::updateOrCreate(
                ['name' => $theme['name']],
                $theme
            );
        }
    }
}
